name = "iruyotua"
main = "src/index.ts"
compatibility_date = "2023-05-11"

[triggers]
crons = ["*/30 * * * *"]

[vars]
# CGAS_API_KEY
# DISCORD_WEBHOOK_URL

# secrets below are only used for slash command
# DISCORD_APPLICATION_ID?
# DISCORD_APPLICATION_PUBLIC_KEY?
# DISCORD_APPLICATION_TOKEN?
